name: Test

on: ["push", "pull_request"]

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mongodb-version: [5.0]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies for the client
        run:  |
              pip3 install -r requirements.txt
              pip install -e .
        shell: bash

      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Test
        run: make test
